project:
  type: website

website:
  title: "CNRA_groundwater"
  navbar:
    left:
      - href: dashboard.qmd
        text: Home
      - href: dashboard.qmd
        text: groundwater

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



